# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "130f43b76720e5251ca1e17421a6a1cd"
name = "PS Store Migration App"
handle = "ps-store-migration-app-12"
application_url = "https://branded-projection-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jkpshoping.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://branded-projection-app.onrender.com/auth/callback",
  "https://branded-projection-app.onrender.com/auth/shopify/callback",
  "https://branded-projection-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
